language: node_js
node_js:
  - "4.0"
  - "4"
  - "5.0"
  - "5"
  - "6.0"
  - "6"
before_install:
  - "npm install -g npm@latest"
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_script:
    - mysql -u root -e "CREATE DATABASE testQueue;"
    - mysql -u root -e "CREATE TABLE queue (hash CHAR(64), PRIMARY KEY(hash));" -D "testQueue"
    - mysql -u root -e "ALTER TABLE queue ADD COLUMN messageBase64 VARCHAR(120) NOT NULL;" -D "testQueue"
    - mysql -u root -e "ALTER TABLE queue ADD COLUMN requeued BOOLEAN DEFAULT FALSE;" -D "testQueue"
    - mysql -u root -e "ALTER TABLE queue ADD COLUMN heartbeatDate DATETIME;" -D "testQueue"
    - mysql -u root -e "ALTER TABLE queue ADD COLUMN owner VARCHAR(256);" -D "testQueue"
    - mysql -u root -e "ALTER TABLE queue ADD COLUMN (isProcessing BOOLEAN DEFAULT FALSE, INDEX isProcessing(isProcessing));" -D "testQueue"
    - mysql -u root -e "ALTER TABLE queue ADD COLUMN topics VARCHAR(256);" -D "testQueue"
script:
  - node bin/manual-testing/wrapped-message-tests
  - node bin/manual-testing/send-message-test
  - node bin/manual-testing/polling-heartbeat-test
